---
- hosts: vagrant
  user: vagrant
  sudo: yes
  tasks: 
    - name: Update apt cache
      apt: update-cache=yes cache_valid_time=86400

    - name: Update all packages
      apt: upgrade=dist

    - name: Install build-essential
      apt: pkg=build-essential

# vboxadditions playbook will detect a mismatch between the host VBox version and Guest Addtitions on the box
# and will update it automatically.  It's ok to run this multiple times, it won't do anything if the correct
# version is installed      
- include: vboxadditions.yaml 